name: Hello World

on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log Level'
        required: true
        default: 'warning'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, World!"