name: post welcome message
on:
    pull_request:
        types: [opened]
permissions:
    pull-requests: write
jobs:
    build:
        name: Post a welcome comment
        runs-on: ubuntu-latest
